# Nostr-rs-relay configuration

[info]
relay_url = "wss://nostr.asits.icu/"
name = "personal-relay"
description = "Relay used as a redundancy."

# Administrative contact pubkey (32-byte hex, not npub)
pubkey = "npub1wvmdt5l7lywle680a7uj9ccjuq5qg0zu8a7gfklhaw8eurff4dcqd9dya4"

# Administrative contact URI
#contact = "mailto:contact@example.com"

# Favicon location.  Relative to the current directory.  Assumes an
# ICO format.
#favicon = "favicon.ico"

# URL of Relay's icon.
#relay_icon = "https://example.test/img.png"

[diagnostics]
# Enable tokio tracing (for use with tokio-console)
#tracing = false

[database]

[logging]

[grpc]

[network]
# Bind to this network address
address = "0.0.0.0"

# Listen on this port
port = 9380

[options]
reject_future_seconds = 1800

[limits]
messages_per_sec = 5
subscriptions_per_min = 10
limit_scrapers = false

[authorization]
pubkey_whitelist = [
  "npub1wvmdt5l7lywle680a7uj9ccjuq5qg0zu8a7gfklhaw8eurff4dcqd9dya4",
]

[verified_users]

[pay_to_relay]
